package com.gracefinance.gracefinanceapp.domain.principal;

import static com.gracefinance.gracefinanceapp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

import com.gracefinance.gracefinanceapp.domain.principal.Caisse;

public class CaisseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCaisseAllPropertiesEquals(Caisse expected, Caisse actual) {
        assertCaisseAutoGeneratedPropertiesEquals(expected, actual);
        assertCaisseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCaisseAllUpdatablePropertiesEquals(Caisse expected, Caisse actual) {
        assertCaisseUpdatableFieldsEquals(expected, actual);
        assertCaisseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCaisseAutoGeneratedPropertiesEquals(Caisse expected, Caisse actual) {
        assertThat(actual)
            .as("Verify Caisse auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCaisseUpdatableFieldsEquals(Caisse expected, Caisse actual) {
        assertThat(actual)
            .as("Verify Caisse relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getDevise()).as("check devise").isEqualTo(expected.getDevise()))
            .satisfies(a -> assertThat(a.getSolde()).as("check solde").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getSolde()))
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCaisseUpdatableRelationshipsEquals(Caisse expected, Caisse actual) {
        assertThat(actual)
            .as("Verify Caisse relationships")
            .satisfies(a -> assertThat(a.getEntiteFinanciere()).as("check entiteFinanciere").isEqualTo(expected.getEntiteFinanciere()));
    }
}
