package com.gracefinance.gracefinanceapp.domain.principal;

import static org.assertj.core.api.Assertions.assertThat;

import com.gracefinance.gracefinanceapp.domain.referentiel.Categorie;

public class CategorieAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategorieAllPropertiesEquals(Categorie expected, Categorie actual) {
        assertCategorieAutoGeneratedPropertiesEquals(expected, actual);
        assertCategorieAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategorieAllUpdatablePropertiesEquals(Categorie expected, Categorie actual) {
        assertCategorieUpdatableFieldsEquals(expected, actual);
        assertCategorieUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategorieAutoGeneratedPropertiesEquals(Categorie expected, Categorie actual) {
        assertThat(actual)
            .as("Verify Categorie auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategorieUpdatableFieldsEquals(Categorie expected, Categorie actual) {
        assertThat(actual)
            .as("Verify Categorie relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getTypeCategorie()).as("check typeCategorie").isEqualTo(expected.getTypeCategorie()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategorieUpdatableRelationshipsEquals(Categorie expected, Categorie actual) {
        assertThat(actual)
            .as("Verify Categorie relationships")
            .satisfies(a -> assertThat(a.getEntiteFinanciere()).as("check entiteFinanciere").isEqualTo(expected.getEntiteFinanciere()));
    }
}
