package com.gracefinance.gracefinanceapp.domain.principal;

import static org.assertj.core.api.Assertions.assertThat;

import com.gracefinance.gracefinanceapp.domain.principal.CompteComptable;

public class CompteComptableAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompteComptableAllPropertiesEquals(CompteComptable expected, CompteComptable actual) {
        assertCompteComptableAutoGeneratedPropertiesEquals(expected, actual);
        assertCompteComptableAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompteComptableAllUpdatablePropertiesEquals(CompteComptable expected, CompteComptable actual) {
        assertCompteComptableUpdatableFieldsEquals(expected, actual);
        assertCompteComptableUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompteComptableAutoGeneratedPropertiesEquals(CompteComptable expected, CompteComptable actual) {
        assertThat(actual)
            .as("Verify CompteComptable auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompteComptableUpdatableFieldsEquals(CompteComptable expected, CompteComptable actual) {
        assertThat(actual)
            .as("Verify CompteComptable relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getLibelle()).as("check libelle").isEqualTo(expected.getLibelle()))
            .satisfies(a -> assertThat(a.getClasse()).as("check classe").isEqualTo(expected.getClasse()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompteComptableUpdatableRelationshipsEquals(CompteComptable expected, CompteComptable actual) {
        // empty method
    }
}
