package com.gracefinance.gracefinanceapp.domain.principal;

import static com.gracefinance.gracefinanceapp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class DepenseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepenseAllPropertiesEquals(Depense expected, Depense actual) {
        assertDepenseAutoGeneratedPropertiesEquals(expected, actual);
        assertDepenseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepenseAllUpdatablePropertiesEquals(Depense expected, Depense actual) {
        assertDepenseUpdatableFieldsEquals(expected, actual);
        assertDepenseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepenseAutoGeneratedPropertiesEquals(Depense expected, Depense actual) {
        assertThat(actual)
            .as("Verify Depense auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepenseUpdatableFieldsEquals(Depense expected, Depense actual) {
        assertThat(actual)
            .as("Verify Depense relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getDateDepense()).as("check dateDepense").isEqualTo(expected.getDateDepense()))
            .satisfies(a ->
                assertThat(a.getMontant()).as("check montant").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getMontant())
            )
            .satisfies(a -> assertThat(a.getMotif()).as("check motif").isEqualTo(expected.getMotif()))
            .satisfies(a -> assertThat(a.getReferencePiece()).as("check referencePiece").isEqualTo(expected.getReferencePiece()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getValiderPar()).as("check validerPar").isEqualTo(expected.getValiderPar()))
            .satisfies(a -> assertThat(a.getDateValidation()).as("check dateValidation").isEqualTo(expected.getDateValidation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepenseUpdatableRelationshipsEquals(Depense expected, Depense actual) {
        assertThat(actual)
            .as("Verify Depense relationships")
            .satisfies(a -> assertThat(a.getEntiteFinanciere()).as("check entiteFinanciere").isEqualTo(expected.getEntiteFinanciere()))
            .satisfies(a -> assertThat(a.getCaisse()).as("check caisse").isEqualTo(expected.getCaisse()))
            .satisfies(a -> assertThat(a.getCategorie()).as("check categorie").isEqualTo(expected.getCategorie()));
    }
}
