package com.gracefinance.gracefinanceapp.domain.principal;

import static org.assertj.core.api.Assertions.assertThat;

public class EcritureComptableAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEcritureComptableAllPropertiesEquals(EcritureComptable expected, EcritureComptable actual) {
        assertEcritureComptableAutoGeneratedPropertiesEquals(expected, actual);
        assertEcritureComptableAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEcritureComptableAllUpdatablePropertiesEquals(EcritureComptable expected, EcritureComptable actual) {
        assertEcritureComptableUpdatableFieldsEquals(expected, actual);
        assertEcritureComptableUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEcritureComptableAutoGeneratedPropertiesEquals(EcritureComptable expected, EcritureComptable actual) {
        assertThat(actual)
            .as("Verify EcritureComptable auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEcritureComptableUpdatableFieldsEquals(EcritureComptable expected, EcritureComptable actual) {
        assertThat(actual)
            .as("Verify EcritureComptable relevant properties")
            .satisfies(a -> assertThat(a.getDateComptable()).as("check dateComptable").isEqualTo(expected.getDateComptable()))
            .satisfies(a -> assertThat(a.getNumeroPiece()).as("check numeroPiece").isEqualTo(expected.getNumeroPiece()))
            .satisfies(a -> assertThat(a.getLibelle()).as("check libelle").isEqualTo(expected.getLibelle()))
            .satisfies(a -> assertThat(a.getReferenceExterne()).as("check referenceExterne").isEqualTo(expected.getReferenceExterne()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEcritureComptableUpdatableRelationshipsEquals(EcritureComptable expected, EcritureComptable actual) {
        // empty method
    }
}
