package com.gracefinance.gracefinanceapp.domain.principal;

import static org.assertj.core.api.Assertions.assertThat;

import com.gracefinance.gracefinanceapp.domain.principal.EntiteFinanciere;

public class EntiteFinanciereAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntiteFinanciereAllPropertiesEquals(EntiteFinanciere expected, EntiteFinanciere actual) {
        assertEntiteFinanciereAutoGeneratedPropertiesEquals(expected, actual);
        assertEntiteFinanciereAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntiteFinanciereAllUpdatablePropertiesEquals(EntiteFinanciere expected, EntiteFinanciere actual) {
        assertEntiteFinanciereUpdatableFieldsEquals(expected, actual);
        assertEntiteFinanciereUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntiteFinanciereAutoGeneratedPropertiesEquals(EntiteFinanciere expected, EntiteFinanciere actual) {
        assertThat(actual)
            .as("Verify EntiteFinanciere auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntiteFinanciereUpdatableFieldsEquals(EntiteFinanciere expected, EntiteFinanciere actual) {
        assertThat(actual)
            .as("Verify EntiteFinanciere relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntiteFinanciereUpdatableRelationshipsEquals(EntiteFinanciere expected, EntiteFinanciere actual) {
        assertThat(actual)
            .as("Verify EntiteFinanciere relationships")
            .satisfies(a -> assertThat(a.getEgliseLiees()).as("check egliseLiees").isEqualTo(expected.getEgliseLiees()))
            .satisfies(a -> assertThat(a.getStructureLiees()).as("check structureLiees").isEqualTo(expected.getStructureLiees()));
    }
}
