package com.gracefinance.gracefinanceapp.domain.principal;

import static com.gracefinance.gracefinanceapp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

import com.gracefinance.gracefinanceapp.domain.principal.LigneEcriture;

public class LigneEcritureAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneEcritureAllPropertiesEquals(LigneEcriture expected, LigneEcriture actual) {
        assertLigneEcritureAutoGeneratedPropertiesEquals(expected, actual);
        assertLigneEcritureAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneEcritureAllUpdatablePropertiesEquals(LigneEcriture expected, LigneEcriture actual) {
        assertLigneEcritureUpdatableFieldsEquals(expected, actual);
        assertLigneEcritureUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneEcritureAutoGeneratedPropertiesEquals(LigneEcriture expected, LigneEcriture actual) {
        assertThat(actual)
            .as("Verify LigneEcriture auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneEcritureUpdatableFieldsEquals(LigneEcriture expected, LigneEcriture actual) {
        assertThat(actual)
            .as("Verify LigneEcriture relevant properties")
            .satisfies(a ->
                assertThat(a.getMontant()).as("check montant").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getMontant())
            )
            .satisfies(a -> assertThat(a.getSens()).as("check sens").isEqualTo(expected.getSens()))
            .satisfies(a -> assertThat(a.getLibelle()).as("check libelle").isEqualTo(expected.getLibelle()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneEcritureUpdatableRelationshipsEquals(LigneEcriture expected, LigneEcriture actual) {
        assertThat(actual)
            .as("Verify LigneEcriture relationships")
            .satisfies(a -> assertThat(a.getEcriture()).as("check ecriture").isEqualTo(expected.getEcriture()))
            .satisfies(a -> assertThat(a.getCompte()).as("check compte").isEqualTo(expected.getCompte()));
    }
}
