package com.gracefinance.gracefinanceapp.domain.principal;

import static com.gracefinance.gracefinanceapp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class RecetteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecetteAllPropertiesEquals(Recette expected, Recette actual) {
        assertRecetteAutoGeneratedPropertiesEquals(expected, actual);
        assertRecetteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecetteAllUpdatablePropertiesEquals(Recette expected, Recette actual) {
        assertRecetteUpdatableFieldsEquals(expected, actual);
        assertRecetteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecetteAutoGeneratedPropertiesEquals(Recette expected, Recette actual) {
        assertThat(actual)
            .as("Verify Recette auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecetteUpdatableFieldsEquals(Recette expected, Recette actual) {
        assertThat(actual)
            .as("Verify Recette relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getDateRecette()).as("check dateRecette").isEqualTo(expected.getDateRecette()))
            .satisfies(a ->
                assertThat(a.getMontant()).as("check montant").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getMontant())
            )
            .satisfies(a -> assertThat(a.getTypeRecette()).as("check typeRecette").isEqualTo(expected.getTypeRecette()))
            .satisfies(a -> assertThat(a.getAnonyme()).as("check anonyme").isEqualTo(expected.getAnonyme()))
            .satisfies(a -> assertThat(a.getMembreNom()).as("check membreNom").isEqualTo(expected.getMembreNom()))
            .satisfies(a -> assertThat(a.getMotif()).as("check motif").isEqualTo(expected.getMotif()))
            .satisfies(a -> assertThat(a.getReferencePiece()).as("check referencePiece").isEqualTo(expected.getReferencePiece()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecetteUpdatableRelationshipsEquals(Recette expected, Recette actual) {
        assertThat(actual)
            .as("Verify Recette relationships")
            .satisfies(a -> assertThat(a.getEntiteFinanciere()).as("check entiteFinanciere").isEqualTo(expected.getEntiteFinanciere()))
            .satisfies(a -> assertThat(a.getCaisse()).as("check caisse").isEqualTo(expected.getCaisse()))
            .satisfies(a -> assertThat(a.getCategorie()).as("check categorie").isEqualTo(expected.getCategorie()));
    }
}
