package com.gracefinance.gracefinanceapp.domain.security;

import static org.assertj.core.api.Assertions.assertThat;

import com.gracefinance.gracefinanceapp.domain.security.Droit;

public class DroitAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDroitAllPropertiesEquals(Droit expected, Droit actual) {
        assertDroitAutoGeneratedPropertiesEquals(expected, actual);
        assertDroitAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDroitAllUpdatablePropertiesEquals(Droit expected, Droit actual) {
        assertDroitUpdatableFieldsEquals(expected, actual);
        assertDroitUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDroitAutoGeneratedPropertiesEquals(Droit expected, Droit actual) {
        assertThat(actual)
            .as("Verify Droit auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDroitUpdatableFieldsEquals(Droit expected, Droit actual) {
        assertThat(actual)
            .as("Verify Droit relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDroitUpdatableRelationshipsEquals(Droit expected, Droit actual) {
        assertThat(actual)
            .as("Verify Droit relationships")
            .satisfies(a -> assertThat(a.getProfils()).as("check profils").isEqualTo(expected.getProfils()));
    }
}
