package com.gracefinance.gracefinanceapp.domain.security;

import static org.assertj.core.api.Assertions.assertThat;

import com.gracefinance.gracefinanceapp.domain.security.Profil;

public class ProfilAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfilAllPropertiesEquals(Profil expected, Profil actual) {
        assertProfilAutoGeneratedPropertiesEquals(expected, actual);
        assertProfilAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfilAllUpdatablePropertiesEquals(Profil expected, Profil actual) {
        assertProfilUpdatableFieldsEquals(expected, actual);
        assertProfilUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfilAutoGeneratedPropertiesEquals(Profil expected, Profil actual) {
        assertThat(actual)
            .as("Verify Profil auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfilUpdatableFieldsEquals(Profil expected, Profil actual) {
        assertThat(actual)
            .as("Verify Profil relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfilUpdatableRelationshipsEquals(Profil expected, Profil actual) {
        assertThat(actual)
            .as("Verify Profil relationships")
            .satisfies(a -> assertThat(a.getDroits()).as("check droits").isEqualTo(expected.getDroits()))
            .satisfies(a -> assertThat(a.getAffectations()).as("check affectations").isEqualTo(expected.getAffectations()));
    }
}
