package com.gracefinance.gracefinanceapp.domain.referentiel;

import static com.gracefinance.gracefinanceapp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

import com.gracefinance.gracefinanceapp.domain.referentiel.Transfert;

public class TransfertAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransfertAllPropertiesEquals(Transfert expected, Transfert actual) {
        assertTransfertAutoGeneratedPropertiesEquals(expected, actual);
        assertTransfertAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransfertAllUpdatablePropertiesEquals(Transfert expected, Transfert actual) {
        assertTransfertUpdatableFieldsEquals(expected, actual);
        assertTransfertUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransfertAutoGeneratedPropertiesEquals(Transfert expected, Transfert actual) {
        assertThat(actual)
            .as("Verify Transfert auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransfertUpdatableFieldsEquals(Transfert expected, Transfert actual) {
        assertThat(actual)
            .as("Verify Transfert relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getDateTransfert()).as("check dateTransfert").isEqualTo(expected.getDateTransfert()))
            .satisfies(a ->
                assertThat(a.getMontant()).as("check montant").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getMontant())
            )
            .satisfies(a -> assertThat(a.getMotif()).as("check motif").isEqualTo(expected.getMotif()))
            .satisfies(a -> assertThat(a.getTypeTransfert()).as("check typeTransfert").isEqualTo(expected.getTypeTransfert()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getValiderPar()).as("check validerPar").isEqualTo(expected.getValiderPar()))
            .satisfies(a -> assertThat(a.getDateValidation()).as("check dateValidation").isEqualTo(expected.getDateValidation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransfertUpdatableRelationshipsEquals(Transfert expected, Transfert actual) {
        assertThat(actual)
            .as("Verify Transfert relationships")
            .satisfies(a ->
                assertThat(a.getEntiteFinanciereSource()).as("check entiteFinanciereSource").isEqualTo(expected.getEntiteFinanciereSource())
            )
            .satisfies(a -> assertThat(a.getCaisseSource()).as("check caisseSource").isEqualTo(expected.getCaisseSource()))
            .satisfies(a -> assertThat(a.getCaisseDestination()).as("check caisseDestination").isEqualTo(expected.getCaisseDestination()));
    }
}
